import type { Apartment } from "../types";

export const homes: Apartment[] = [
  {
    id: 1,
    buildingNumber: "14B",
    floorNumber: "3",
    city: "Minya",
    area: "University Area",
    district: "حي الجامعة",
    address: "شارع الجامعة",
    fullLocation: "المنيا حي الجامعة",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85",
    ],
    price: 1850,
    rating: 4.9,
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85",
    beds: 8,
    rooms: 3,
    amenities: ["wifi", "air-conditioning", "private-bathroom", "security"],
    allowedGender: "any",
    publisherRole: "OWNER",
    ownerId: "user-owner-001",
    publisherName: "Ahmed Ali",
    publisherPhone: "01000000001",
  },
  {
    id: 2,
    buildingNumber: "8A",
    floorNumber: "2",
    city: "Minya",
    area: "Downtown",
    district: "وسط البلد",
    address: "شارع الجمهورية",
    fullLocation: "المنيا وسط البلد",
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    ],
    price: 1400,
    rating: 4.7,
    image:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    beds: 6,
    rooms: 2,
    amenities: ["wifi", "security"],
    allowedGender: "any",
    publisherRole: "BROKER",
    ownerId: "user-broker-001",
    publisherName: "Omar Hassan",
    publisherPhone: "01000000002",
  },
  {
    id: 3,
    buildingNumber: "22",
    floorNumber: "5",
    city: "Cairo",
    area: "Nasr City",
    district: "Nasr City",
    address: "University Street",
    fullLocation: "Cairo Nasr City University Street",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=85",
    ],
    price: 3200,
    rating: 4.8,
    image:
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=85",
    beds: 12,
    rooms: 6,
    amenities: [
      "wifi",
      "air-conditioning",
      "private-bathroom",
      "security",
      "natural-gas",
      "elevator",
    ],
    allowedGender: "any",
    publisherRole: "OWNER",
    ownerId: "user-owner-001",
    publisherName: "Mona Adel",
    publisherPhone: "01000000003",
  },
  {
    id: 4,
    buildingNumber: "31",
    floorNumber: "4",
    city: "Alexandria",
    area: "Sidi Gaber",
    district: "Sidi Gaber",
    address: "Corniche Road",
    fullLocation: "Alexandria Sidi Gaber Corniche Road",
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85",
    ],
    price: 2400,
    rating: 4.6,
    image:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1000&q=85",
    beds: 10,
    rooms: 4,
    amenities: ["wifi", "private-bathroom", "security"],
    allowedGender: "any",
    publisherRole: "BROKER",
    ownerId: "user-broker-001",
    publisherName: "Nour Ibrahim",
    publisherPhone: "01000000004",
  },
  {
    id: 5,
    buildingNumber: "17",
    floorNumber: "1",
    city: "Minya",
    area: "University Area",
    district: "حي الجامعة",
    address: "شارع كلية الطب",
    fullLocation: "المنيا جامعة المنيا حي الجامعة",
    images: [
      "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1000&q=85",
    ],
    price: 2100,
    rating: 4.5,
    image:
      "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1000&q=85",
    beds: 8,
    rooms: 3,
    amenities: ["wifi", "air-conditioning"],
    allowedGender: "any",
    publisherRole: "OWNER",
    ownerId: "user-owner-001",
    publisherName: "Sara Mostafa",
    publisherPhone: "01000000005",
  },
];

export const text = {
  en: {
    home: "Home",
    explore: "Explore homes",
    how: "How it works",
    owners: "For owners",
    sign: "Sign in",
    join: "Create account",
    title: "Find your perfect student home",
    desc: "Verified rooms, honest prices, and a community that makes university life feel like home.",
    search: "Search homes",
    featured: "Homes worth coming home to",
    buildingNumber: "Building Number",
    floorNumber: "Floor Number",
  },
  ar: {
    home: "الرئيسية",
    explore: "استكشف السكن",
    how: "كيف تعمل المنصة",
    owners: "لأصحاب العقارات",
    sign: "تسجيل الدخول",
    join: "إنشاء حساب",
    title: "اعثر على بيتك الطلابي المثالي",
    desc: "غرف موثوقة وأسعار واضحة ومجتمع يجعل الحياة الجامعية أقرب إلى المنزل.",
    search: "ابحث عن سكن",
    featured: "بيوت تستحق العودة إليها",
  },
} as const;
